---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Deploy Nephio packages
  ansible.builtin.include_role:
    name: kpt
  loop:
    - {pkg: porch-dev, version: porch-dev/v1, namespaces: [porch-fn-system, porch-system]}
    - {pkg: nephio-controllers, version: nephio-controllers/v1, namespaces: [nephio-system]}
    - {pkg: configsync, version: configsync/v1, namespaces: [config-management-monitoring, config-management-system, resource-group-system]}
    - {pkg: nephio-stock-repos, version: stock-repos, namespaces: []}
  vars:
    repo_uri: https://github.com/nephio-project/nephio-example-packages.git
    local_dest_directory: /tmp
    pkg: "{{ item.pkg }}"
    version: "{{ item.version }}"
    namespaces: "{{ item.namespaces }}"
    context: kind-kind
- name: Create gitea user password in nephio-system namespace
  become: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: git-user-secret
        namespace: nephio-system
      type: kubernetes.io/basic-auth
      stringData:
        username: "{{ gitea_username }}"
        password: "{{ gitea_password }}"

### TEST CODE - after webui merges to the main repo, the repo_uri and version should change
- name: Deploy Nephio webui
  ansible.builtin.include_role:
    name: kpt
  loop:
    - {pkg: nephio-webui, version: pv-pvs-viewers, namespaces: [nephio-webui]}
  vars:
    repo_uri: https://github.com/johnbelamaric/nephio-packages.git
    local_dest_directory: /tmp
    pkg: "{{ item.pkg }}"
    version: "{{ item.version }}"
    namespaces: "{{ item.namespaces }}"
    context: kind-kind
