---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Deploy Nephio packages
  ansible.builtin.include_role:
    name: kpt
  loop:
    - {pkg: porch-dev, version: porch-dev/v1, namespaces: [porch-fn-system, porch-system]}
    - {pkg: nephio-controllers, version: nephio-controllers/v1, namespaces: [nephio-system]}
    - {pkg: configsync, version: configsync/v1, namespaces: [config-management-monitoring, config-management-system, resource-group-system]}
  vars:
    repo_uri: https://github.com/nephio-project/nephio-example-packages
    local_dest_directory: /tmp
    pkg: "{{ item.pkg }}"
    version: "{{ item.version }}"
    namespaces: "{{ item.namespaces }}"
    context: kind-kind
- name: Create /tmp/rootsync
  file:
    path: /tmp/rootsync
    state: directory
- name: Deploy repo and rootsync
  ansible.builtin.include_role:
    name: kpt
  loop:
    - {pkg: repository, version: repository/v2, localdir: "/tmp/mgmt"}
    - {pkg: rootsync, version: rootsync/v2, localdir: "/tmp/rootsync/mgmt"}
  vars:
    repo_uri: https://github.com/nephio-project/nephio-example-packages
    local_dest_directory: "{{ item.localdir }}"
    pkg: "{{ item.pkg }}"
    version: "{{ item.version }}"
    namespaces: "{{ item.namespaces }}"
    context: kind-kind
### TEST CODE - after webui merges to the main repo, this can be combined above
- name: Deploy Nephio webui
  ansible.builtin.include_role:
    name: kpt
  loop:
    - {pkg: nephio-webui, version: pv-pvs-viewers, namespaces: [nephio-webui]}
  vars:
    repo_uri: https://github.com/johnbelamaric/nephio-example-packages
    local_dest_directory: /tmp
    pkg: "{{ item.pkg }}"
    version: "{{ item.version }}"
    namespaces: "{{ item.namespaces }}"
    context: kind-kind
